# Generated by Django 5.1.3 on 2024-11-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel_search", "0002_channelsearch_has_new_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelsearch",
            name="channel_id",
            field=models.CharField(default="UNKNOWN", max_length=100),
            preserve_default=False,
        ),
    ]
